artifact_location: file:///D:/best_mukul_self_made/Project3_Telecom_Customer_Churn_Prediction_System/MLFLOW_TRACKING_URI/0
creation_time: 1777698012843
experiment_id: '0'
last_update_time: 1777698012843
lifecycle_stage: active
name: Default
workspace: default
