artifact_uri: file:///D:/best_mukul_self_made/Project3_Telecom_Customer_Churn_Prediction_System/MLFLOW_TRACKING_URI/736507650479348050/c0f101dd972940899f9fc2f7a6c26fee/artifacts
end_time: 1777698029135
entry_point_name: ''
experiment_id: '736507650479348050'
lifecycle_stage: active
run_id: c0f101dd972940899f9fc2f7a6c26fee
run_name: unruly-penguin-385
source_name: ''
source_type: 4
source_version: ''
start_time: 1777698014401
status: 3
tags: []
user_id: Mukul9112003
