artifact_location: file:///D:/best_mukul_self_made/Project3_Telecom_Customer_Churn_Prediction_System/MLFLOW_TRACKING_URI/736507650479348050
creation_time: 1777698012899
experiment_id: '736507650479348050'
last_update_time: 1777698012899
lifecycle_stage: active
name: churn_prediction
workspace: default
